version: "3.4"
services:
  # NGINX
  nginx:
    image: nginx_otel:latest
    container_name: nginx
    volumes:
      - type: bind
        source: ./opentelemetry_module.conf
        target: /opt/opentelemetry_module.conf
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "80:80"

  # OTel Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: "--config=/etc/otel-collector-config.yaml ${OTELCOL_ARGS}"
    # Change the "source" path below to swap out collector config files!
    volumes:
      - type: bind
        source: ./otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
      - "55681:55681" # http
    depends_on:
      - nginx
  
